CREATE TABLE MENU
(
  OBJECT_ID     VARCHAR(30) PRIMARY KEY,
  OBJECT_NM     VARCHAR(50) NOT NULL,
  PARENT_ID     VARCHAR(30),
  OPEN_YN       CHAR(1)     DEFAULT 'Y'  NOT NULL,
  SQ            VARCHAR(10),
  FILE_PATH     VARCHAR(100),
  NOTE          VARCHAR(100)
);

CREATE TABLE SQLMAP (
	KEY_ VARCHAR(100) PRIMARY KEY,
	SQL_ VARCHAR(100) NOT NULL
);

CREATE TABLE USER (
	ID 			VARCHAR(50) PRIMARY KEY,
	NAME 		VARCHAR(50) NOT NULL,
	PASSWORD 	VARCHAR(50) NOT NULL
);